name: life_time_app
description: Life time application

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flare_flutter: any

flutter:
  uses-material-design: true

  assets:
    - assets/animation/LoadingAnimation.flr
    - assets/images/cat.jpeg
    - assets/images/dog.jpg
    - assets/images/raccoon.jpg

  fonts:
    - family: IndieFlower
      fonts:
        - asset:  assets/fonts/IndieFlower-Regular.ttf
